apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: component-sample
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/sample-image@sha256:33d9e33ecc2a2910f967fc2e95f8a64872e9d1e31d00f763a442a8866b391b6c
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
